### PR TITLE
Update auth_googleoauth2.php

### PR DESCRIPTION
**Pull request by crazyserver**

### CODE REVIEW

**Comment by mouneyrac** [comment]
this has been fixed somewhere in my previous commits Pau, thanks for the pull request.

**Comment by mouneyrac** [comment]
lol google translate automatically change the es in en... merging

**Comment by mouneyrac** [comment]
thanks Pau

**Comment by crazyserver** [comment]
Thank you!!!

I've written in Moodle plugins directory asking for that:

"We have a problem translating the module for 2.8, in AMOS we cannot see versions greater than 2.5 so the new strings are not included."

Please can you check it?

**Comment by mouneyrac** [comment]
I created https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/123

**Pull request merged**
